<a href="https://colab.research.google.com/github/vldzmtnsdl/ESAA-/blob/ESAA/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[NLP 언제까지 미룰래? 일단 들어와!!] #2.NLP 전처리
1. 형태소 분석


1-1 Kkma

In [1]:
pip install konlpy

     |████████████████████████████████| 19.4 MB 1.2 MB/s 
     |████████████████████████████████| 86 kB 4.6 MB/s 
     |████████████████████████████████| 448 kB 62.1 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [1]:
from konlpy.tag import Kkma

In [2]:
kkma=Kkma()

In [3]:
sentence="데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!."

In [4]:
print("형태소 단위로 문장 분리")
print("----------------------")
print(kkma.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("----------------------")
print(kkma.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

형태소 단위로 문장 분리
----------------------
['데이', '콘', '에서', '다양', '하', 'ㄴ', '컴피티션', '을', '즐기', '면서', '실력', '있', '는', '데이터', '분석가', '로', '성장', '하', '세요', '!!', '.']
 
문장에서 명사 추출
----------------------
['데이', '데이콘', '콘', '다양', '컴피티션', '실력', '데이터', '분석가', '성장']
 
품사 태킹(PoS)
----------------------
[('데이', 'NNG'), ('콘', 'NNG'), ('에서', 'JKM'), ('다양', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('컴피티션', 'UN'), ('을', 'JKO'), ('즐기', 'VV'), ('면서', 'ECE'), ('실력', 'NNG'), ('있', 'VV'), ('는', 'ETD'), ('데이터', 'NNG'), ('분석가', 'NNG'), ('로', 'JKM'), ('성장', 'NNG'), ('하', 'XSV'), ('세요', 'EFN'), ('!!', 'SW'), ('.', 'SF')]


1-2 OKt

In [5]:
from konlpy.tag import Okt

In [6]:
Okt=Okt()
sentence="데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!."

In [7]:
print("형태소 단위로 문장 분리")
print("----------------------")
print(Okt.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("----------------------")
print(Okt.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("----------------------")
print(Okt.pos(sentence))

형태소 단위로 문장 분리
----------------------
['데', '이콘', '에서', '다양한', '컴피티션', '을', '즐기면서', '실력', '있는', '데이터', '분석', '가로', '성장하세요', '!!.']
 
문장에서 명사 추출
----------------------
['데', '이콘', '컴피티션', '실력', '데이터', '분석', '가로']
 
품사 태킹(PoS)
----------------------
[('데', 'Noun'), ('이콘', 'Noun'), ('에서', 'Josa'), ('다양한', 'Adjective'), ('컴피티션', 'Noun'), ('을', 'Josa'), ('즐기면서', 'Verb'), ('실력', 'Noun'), ('있는', 'Adjective'), ('데이터', 'Noun'), ('분석', 'Noun'), ('가로', 'Noun'), ('성장하세요', 'Adjective'), ('!!.', 'Punctuation')]


1-3.Mecab

In [14]:
from konlpy.tag import Mecab
Mecab=Mecab()
sentence="데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!."

Exception: ignored

2. 표제어 추출

In [15]:
from konlpy.tag import Kkma
kkma=Kkma()

sentence="성장했었다."

print("품사 태깅(PoS")
print('---------')
print(kkma.pos(sentence))

품사 태깅(PoS
---------
[('성장', 'NNG'), ('하', 'XSV'), ('었', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


In [16]:
sentence="성장하였었다."

print('품사 태깅(PoS)')
print('----------')
print(kkma.pos(sentence))

품사 태깅(PoS)
----------
[('성장', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


3. 불용어 제거

In [17]:
import re
from konlpy.tag import Okt
tokenizer=Okt()
def text_preprocessing(text,tokenizer):

  stopwords=['을','를','이','가','은','는']

  txt=re.sub('[^가-힣a-z]','',text)
  token=tokenizer.morphs(txt)
  token=[t for t in token if t not in stopwords]

  return token

ex_text = "이번에 새롭게 개봉한 영화의 배우들은 모두 훌륭한 연기력과 아름다운 목소리를 갖고 있어!!"
example_pre=text_preprocessing(ex_text,tokenizer)

In [18]:
print(example_pre)

['이번', '에', '새롭게', '개봉', '한', '영화', '의', '배우', '들', '모두', '훌륭한', '연기력', '과', '아름다운', '목소리', '갖고있어']


4. 대회 적용

In [19]:
def text_preprocessing(text_list):

  stopwords=['을','를','이','가','은','는','null']
  tokenizer=Okt()
  token_list=[]

  for text in text_list:
    txt=re.sub('[^가-힣a-z]', ' ', text) # 한글과 영어 소문자만 남기고 다른 글자 모두 제거
    token=tokenizer.morphs(txt)
    token=[t for t in token if t not in stopwords or type(t)!=float]
    token_list.append(token)
  return token_list,tokenizer

train['new_article'],okt=text_preprocessing(train['content'])

NameError: ignored

Facebook의 fasttext를 이용한 text classification

In [13]:
pip install fasttext

In [20]:
import fasttext
import pandas as pd
import numpy as np



In [21]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [22]:
path='/content/gdrive/My Drive'

In [23]:
train=pd.read_csv('train.csv')

In [24]:
file=open('fasttexttrain.txt','w+')
for i in train.index:
  line='_label_'+ str(train['author'][i])+''+train['text'][i]
  file.write(line+'\n')

  

In [ ]:
text_clf_model=fasttext.train_supervised('fasttexttrain.txt')
print(text_clf_model.words)
print(text_clf_model.labels)

result=text_clf_model.predict('He was almost choking.There was so much, so much he wanted to say, but strange exclamations were all that came from his lips. The Pole gazed fixedly at him, at the bundle of notes in his hand; looked at odin, and was in evident perplexity.',k=5)
print(result)



In [25]:
test=pd.read_csv('test_x.csv')
submission=pd.read_csv('sample_submission.csv',index_col=False)

FileNotFoundError: ignored

In [26]:
for i in test.index:
    lable, proba = text_clf_model.predict(test['text'][i], k=5)
    for la, pr in zip(lable, proba):
        if '__label__0' == la:
            submission.loc[i, '0'] = pr
        elif '__label__1' == la:
            submission.loc[i, '1'] = pr
        elif '__label__2' == la:
            submission.loc[i, '2'] = pr
        elif '__label__3' == la:
            submission.loc[i, '3'] = pr
        elif '__label__4' == la:
            submission.loc[i, '4'] = pr

submission.to_csv('result5_fasttext.csv',index=False)
print('end')

NameError: ignored

[NLP 언제까지 미룰래? 일단 들어와!!] #3.Vectorization

In [27]:
from konlpy.tag import Okt
import re

Okt=Okt()

In [28]:
sentences = ['자연어 처리는 정말 정말 즐거워.', '즐거운 자연어 처리 다같이 해보자.']
tokens = []

In [29]:
for sentence in sentences:
  sentence=re.sub('[^가-힣a-z]','',sentence)
  token=(Okt.morphs(sentence))
  tokens.append(''.join(token))

print('형태소 단위로 문장 분리')
print('--------------------------')
print(tokens)

형태소 단위로 문장 분리
--------------------------
['자연어처리는정말정말즐거워', '즐거운자연어처리다같이해보자']


1.one hot encoding

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

t=Tokenizer()
t.fit_on_texts(tokens)
print('각 토큰에게 고유의 정수 부여')
print('-------------------------')
print(t.word_index)
print("")

s1=t.texts_to_sequences(tokens)[0]
print('부여된 정수로 표시된 문장1')
print('---------------------')
print(s1)
print('')

s2=t.texts_to_sequences(tokens)[1]
print('부여된 정수로 표시된 문장2')
print('-------------------')
print(s2)
print("")

s1_one_hot=to_categorical(s1)
print('문장1의 one_hot_encoding')
print('------------------')
print(s1_one_hot)
print("")

s2_one_hot=to_categorical(s2)
print('문장2의 one_hot_encoding')
print('------------------')
print(s2_one_hot)

각 토큰에게 고유의 정수 부여
-------------------------
{'자연어처리는정말정말즐거워': 1, '즐거운자연어처리다같이해보자': 2, '자연어': 3, '처리': 4, '정말': 5, '는': 6, '즐거워': 7, '즐거운': 8, '다': 9, '같이': 10, '해보자': 11}

부여된 정수로 표시된 문장1
---------------------
[1]

부여된 정수로 표시된 문장2
-------------------
[2]

문장1의 one_hot_encoding
------------------
[[0. 1.]]

문장2의 one_hot_encoding
------------------
[[0. 0. 1.]]


2. count vectorization

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
vectors=vectorizer.fit_transform(tokens)

print(vectorizer.get_feature_names())
print(vectors.toarray())

['자연어처리는정말정말즐거워', '즐거운자연어처리다같이해보자']
[[1 0]
 [0 1]]


3. tfldf

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(min_df=0)
tfidf_vectorizer=tfidf.fit_transform(tokens)

tfidf_dict=tfidf.get_feature_names()
print(tfidf_dict)
print(tfidf_vectorizer.toarray())


['자연어처리는정말정말즐거워', '즐거운자연어처리다같이해보자']
[[1. 0.]
 [0. 1.]]


4. padding

5. 대회적용

In [29]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text2sequence(train_text,max_len=100):
  tokenizer=Tokenizer()
  tokenizer.fit_on_texts(train_text)
  train_X_seq=tokenizer.texts_to_sequences(train_text)
  vocab_size=len(tokenizer.word_index)+1
  print('vocab_size:',vocab_size)
  X_train=pad_sequences(train_X_seq,maxlen=max_len)

  return X_train,vocab_size,tokenizer

train_X,vocab_size,vectorizer=text2sequence(train['text'],max_len=100)

vocab_size: 42331
