In [16]:
import numpy as np

def cos_similarity(v1,v2):
    dot_product=np.dot(v1,v2)
    l2_norm=(np.sqrt(sum(np.square(v1)))*np.sqrt(sum(np.square(v2))))
    similarity=dot_product/l2_norm
    
    return similarity

In [6]:
v=np.array([1,2,3])
print(np.square(v))

[1 4 9]


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

doc_list=['if you take the blue pill, the story ends','if you take the red pill, you stay in Wonderland',
         'if you take the red pill, I show you how deep the rabbit hole goes']

tfidf_vect_simple=TfidfVectorizer()
feature_vect_simple=tfidf_vect_simple.fit_transform(doc_list)
print(feature_vect_simple.shape)

(3, 18)


In [9]:
feature_vect_dense=feature_vect_simple.todense()

In [12]:
# 희소행렬
print(feature_vect_simple)

  (0, 2)	0.41556360057939173
  (0, 13)	0.41556360057939173
  (0, 8)	0.24543855687841593
  (0, 0)	0.41556360057939173
  (0, 15)	0.49087711375683185
  (0, 14)	0.24543855687841593
  (0, 17)	0.24543855687841593
  (0, 6)	0.24543855687841593
  (1, 16)	0.39624495215024286
  (1, 7)	0.39624495215024286
  (1, 12)	0.39624495215024286
  (1, 10)	0.3013544995034864
  (1, 8)	0.2340286519091622
  (1, 15)	0.2340286519091622
  (1, 14)	0.2340286519091622
  (1, 17)	0.4680573038183244
  (1, 6)	0.2340286519091622
  (2, 3)	0.3098560092999078
  (2, 4)	0.3098560092999078
  (2, 9)	0.3098560092999078
  (2, 1)	0.3098560092999078
  (2, 5)	0.3098560092999078
  (2, 11)	0.3098560092999078
  (2, 10)	0.23565348175165166
  (2, 8)	0.1830059506093466
  (2, 15)	0.3660119012186932
  (2, 14)	0.1830059506093466
  (2, 17)	0.3660119012186932
  (2, 6)	0.1830059506093466


In [14]:
#밀집행렬
print(feature_vect_dense)

[[0.4155636  0.         0.4155636  0.         0.         0.
  0.24543856 0.         0.24543856 0.         0.         0.
  0.         0.4155636  0.24543856 0.49087711 0.         0.24543856]
 [0.         0.         0.         0.         0.         0.
  0.23402865 0.39624495 0.23402865 0.         0.3013545  0.
  0.39624495 0.         0.23402865 0.23402865 0.39624495 0.4680573 ]
 [0.         0.30985601 0.         0.30985601 0.30985601 0.30985601
  0.18300595 0.         0.18300595 0.30985601 0.23565348 0.30985601
  0.         0.         0.18300595 0.3660119  0.         0.3660119 ]]


In [18]:
vect1=np.array(feature_vect_dense[0]).reshape(-1,)
vect2=np.array(feature_vect_dense[1]).reshape(-1,)
vect3=np.array(feature_vect_dense[2]).reshape(-1,)
similarity_simple=cos_similarity(vect1,vect2)
print('문장1, 문장2 Cosine 유사도: {0:.3f}'.format(similarity_simple))
similarity_simple=cos_similarity(vect2,vect3)
print('문장2, 문장3 Cosine 유사도: {0:.3f}'.format(similarity_simple))
similarity_simple=cos_similarity(vect3,vect1)
print('문장3, 문장1 Cosine 유사도: {0:.3f}'.format(similarity_simple))

문장1, 문장2 Cosine 유사도: 0.402
문장2, 문장3 Cosine 유사도: 0.456
문장3, 문장1 Cosine 유사도: 0.404


API이용

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_simple_pair=cosine_similarity(feature_vect_simple[0],feature_vect_simple)
print(similarity_simple_pair)

[[1.         0.40207758 0.40425045]]


In [21]:
similarity_simple_pair=cosine_similarity(feature_vect_simple,feature_vect_simple)
print(similarity_simple_pair)
print('shape:',similarity_simple_pair.shape)

[[1.         0.40207758 0.40425045]
 [0.40207758 1.         0.45647296]
 [0.40425045 0.45647296 1.        ]]
shape: (3, 3)


In [23]:
import pandas as pd
import glob,os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

path=r'C:\Users\jeehy\Desktop\ESAA\ESAA_2021_2학기세션\hw\OpinosisDataset1.0\topics'
all_files=glob.glob(os.path.join(path,"*.data"))
filename_list=[]
opinion_text=[]

In [24]:
for file_ in all_files:
    
    df=pd.read_table(file_,index_col=None,header=0,encoding='latin1')
    
    filename_=file_.split('\\')[-1]
    filename=filename_.split('.')[0]
    
    filename_list.append(filename)
    opinion_text.append(df.to_string())
    
document_df=pd.DataFrame({'filename':filename_list,'opinion_text':opinion_text})
document_df.head()
    

filename  \
0   accuracy_garmin_nuvi_255W_gps   
1  bathroom_bestwestern_hotel_sfo   
2      battery-life_amazon_kindle   
3      battery-life_ipod_nano_8gb   
4     battery-life_netbook_1005ha   

                                        opinion_text  
0                                                ...  
1                                                ...  
2                                                ...  
3                                                ...  
4                                                ...

In [25]:
tfidf_vect=TfidfVectorizer(tokenizer=LemNormalize,stop_words='english',ngram_range=(1,2),min_df=0.05,max_df=0.85)
feature_vect=tfidf_vect.fit_transform(document_df['opinion_text'])

NameError: name 'LemNormalize' is not defined

In [26]:
df.head()

The voice prompts and maps are wonderful especially when driving after dark .
0  I also thought the the voice prompts of the 75...                             
1   The 750 sounds more like a real female voice,...                             
2   I didn't have the problems with the sounds of...                             
3                  Some of the voices are annoying .                             
4   My understanding is that Garmin really compre...