In [5]:
import numpy as np

R=np.array([[4,np.NaN,np.NaN,2,np.NaN],
            [np.NaN,5,np.NaN,3,1],
            [np.NaN,np.NaN,3,4,4],
            [5,2,1,2,np.NaN]])

num_users,num_items=R.shape
K=3

np.random.seed(1)
P=np.random.normal(scale=1./K,size=(num_users,K))
Q=np.random.normal(scale=1./K,size=(num_items,K))

In [6]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
    error=0
    full_pred_matrix=np.dot(P,Q.T)
    
    x_non_zero_ind=[non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind=[non_zero[1] for non_zero in non_zeros]
    R_non_zeros=R[x_non_zero_ind,y_non_zero_ind]
    full_pred_matrix_non_zeros=full_pred_matrix[x_non_zero_ind,y_non_zero_ind]
    mse=mean_squared_error(R_non_zeros,full_pred_matrix_non_zeros)
    rmse=np.sqrt(mse)
    
    return rmse


In [8]:
non_zeros=[ (i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

steps=1000
learning_rate=0.01
r_lambda=0.01

for step in range(steps):
    for i,j,r in non_zeros:
        
        eij=r-np.dot(P[i,:],Q[j,:].T)
        
        P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
        Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])
        
    rmse=get_rmse(R,P,Q,non_zeros)
    if(step%50)==0:
        print('### interation step:',step,"rmse:",rmse)

### interation step: 0 rmse: 3.2388050277987723
### interation step: 50 rmse: 0.4876723101369647
### interation step: 100 rmse: 0.15643403848192458
### interation step: 150 rmse: 0.07455141311978064
### interation step: 200 rmse: 0.043252267985793146
### interation step: 250 rmse: 0.029248328780879226
### interation step: 300 rmse: 0.022621116143829507
### interation step: 350 rmse: 0.019493636196525232
### interation step: 400 rmse: 0.018022719092132773
### interation step: 450 rmse: 0.01731968595344283
### interation step: 500 rmse: 0.016973657887570985
### interation step: 550 rmse: 0.01679680459589558
### interation step: 600 rmse: 0.016701322901884634
### interation step: 650 rmse: 0.016644736912476574
### interation step: 700 rmse: 0.016605910068210012
### interation step: 750 rmse: 0.01657420047570488
### interation step: 800 rmse: 0.01654431582921612
### interation step: 850 rmse: 0.016513751774735037
### interation step: 900 rmse: 0.01648146573819507
### interation step: 950 r

In [9]:
pred_matrix=np.dot(P,Q.T)
print('예측 행렬:\n',np.round(pred_matrix,3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
