In [1]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X,y=make_moons(n_samples=1000,noise=0.05)
dbscan=DBSCAN(eps=0.05,min_samples=5)
dbscan.fit(X)

DBSCAN(eps=0.05)

In [2]:
dbscan.labels_

array([ 0,  1,  0,  2,  0,  3,  4,  3,  2,  0, -1, -1,  2,  4,  1,  2,  5,
        1,  1,  6,  1,  7,  0,  4, -1,  2,  4,  1,  2,  0,  5, -1,  1,  0,
        2,  2,  8,  0,  0, -1,  0,  7,  4,  1, -1,  6,  8,  6,  1,  0,  0,
       -1,  1,  5,  2, -1,  4,  2,  0,  6,  4,  2, -1,  3,  7,  8,  7,  1,
        9,  2,  2,  7,  0,  2,  4,  4,  9,  0,  0,  0,  1,  9,  0,  8,  0,
        1,  9, -1, -1,  3, -1,  9,  0,  2, -1,  0,  1,  2,  4,  1,  0, -1,
        2,  0,  4,  7,  0,  0,  2,  1,  2,  0,  2,  2,  4,  0,  8,  2,  5,
       -1,  0,  0,  6,  1, -1,  1,  0,  1,  2,  2,  3,  3, -1,  0,  2,  1,
        2,  0,  7,  4, -1, -1,  2,  1, -1,  0,  9,  6,  3,  7,  0,  7,  9,
        1,  6,  2,  4,  2,  9,  0,  1, -1,  9,  6, -1, -1,  9,  0,  1,  0,
        8,  1,  1,  0,  1,  5,  1,  1,  0,  4,  2,  7,  8,  0, -1, -1,  7,
       -1,  9,  1,  2,  9,  2,  3,  2,  8,  2,  0,  1,  2,  8,  0,  2,  2,
        5, -1,  6,  6,  1,  2,  1,  1, -1, 11,  2,  1,  6,  0,  1,  0,  5,
        2,  0,  2,  0,  9

In [3]:
len(dbscan.core_sample_indices_)

798

In [5]:
dbscan.core_sample_indices_

array([  0,   1,   2,   3,   4,   5,   7,   8,   9,  12,  13,  14,  15,
        16,  19,  20,  21,  22,  23,  25,  26,  27,  28,  29,  32,  33,
        34,  35,  36,  37,  38,  40,  41,  42,  43,  45,  47,  48,  49,
        50,  52,  53,  56,  57,  58,  59,  60,  61,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        81,  82,  83,  84,  85,  86,  91,  92,  93,  95,  97,  98,  99,
       100, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 116, 117, 118, 120, 122, 126, 127, 128, 129, 130, 131, 133,
       134, 135, 136, 137, 138, 139, 142, 143, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 162, 163,
       166, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 186, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 207, 208, 209, 210,
       211, 214, 215, 216, 217, 218, 219, 220, 222, 223, 224, 22

In [6]:
dbscan.components_

array([[ 1.13019533, -0.51493911],
       [-0.3924974 ,  0.98696789],
       [ 0.7840742 , -0.52555353],
       ...,
       [-0.81540138,  0.51788147],
       [-0.66021428,  0.74200409],
       [ 2.02657885,  0.39743361]])

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_,dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [10]:
import numpy as np

In [11]:
X_new=np.array([[-0.5,0],[0,0.5],[1,-0.1],[2,1]])
knn.predict(X_new)
knn.predict_proba(X_new)

array([[0.  , 0.04, 0.  , 0.  , 0.  , 0.02, 0.  , 0.  , 0.72, 0.12, 0.1 ,
        0.  ],
       [0.  , 0.08, 0.  , 0.  , 0.  , 0.52, 0.  , 0.  , 0.  , 0.4 , 0.  ,
        0.  ],
       [0.3 , 0.  , 0.  , 0.7 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.92, 0.06, 0.  , 0.  , 0.  ,
        0.02]])

In [12]:
y_dist,y_pred_idx=knn.kneighbors(X_new,n_neighbors=1)
y_pred=dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist>0.2]=-1
y_pred.ravel()

array([-1,  5,  3, -1], dtype=int64)